### ISSUE TITLE
Generation hash that is the same as Testnet.

### ISSUE THREAD

**Issue by Wayonb** [CrackTheCode016/cat-config-scripts#3]
First I want to say these scripts are very useful and easy to use.

The generation hash should be different for each instance of the NEM blockchain. When I ran the scripts the generation hash is the same as testnet.

**Comment by CrackTheCode016** [comment]
Thanks for bringing that up!  Will resolve in the next commits (along with other fixes).

**Comment by CrackTheCode016** [comment]
fixed as of f6e88f2, can be use with `--local`
